export default {
  CITY_COORDS: {
    Warrington: { lat: 53.390044, lng: -2.59695 },
    Manchester: { lat: 53.48095, lng: -2.23743 },
  },
  BASE_LISTING_MAP_CIRCLE_RADIUS: 500,
  DEFAULT_PHOTO_LINK: "/images/admin/user-avatar-80.png",
  MAX_SEARCH_INPUT_LENGTH: 255,
  ORDER_STATUSES: {
    PENDING_OWNER: "pending_owner",
    PENDING_TENANT: "pending_tenant",
    PENDING_CLIENT_PAYMENT: "pending_client_payment",
    PENDING_ITEM_TO_CLIENT: "pending_item_to_client",
    IN_PROCESS: "in_process",
    PENDING_ITEM_TO_OWNER: "pending_item_to_owner",
    FINISHED: "finished",
    REJECTED: "rejected",
  },
  ORDER_CANCELATION_STATUSES: {
    WAITING_OWNER_APPROVE: "waiting_owner_approve",
    WAITING_TENANT_APPROVE: "waiting_tenant_approve",
    WAITING_ADMIN_APPROVE: "waiting_admin_approve",
    CANCELLED: "cancelled",
  },
  MIN_PRICE_LIMIT: 1,
  MAX_PRICE_LIMIT: 1000000,
  ORDER_ACTION_BUTTONS: {
    BOOKING_AGREEMENT_SECTION: "booking-agreement-section",
    PAY_BUTTON: "pay-button",
    CANCEL_BUTTON: "cancel-button",
    FOR_TENANT_QRCODE: "for-tenant-qrcode",
    FOR_OWNER_QRCODE: "for-owner-qrcode",
    TENANT_GOT_LISTING_APPROVE_BUTTON: "tenant-got-listing-approve-button",
    CREATE_DISPUTE_BUTTON: "create-dispute-button",
    FAST_CANCEL_BUTTON: "fast-cancel-button",
    ACCEPT_FINISH_BUTTON: "accept-finish-button",
    ACCEPT_OWNER_CANCEL_BUTTON: "accept-owner-cancel-button",
    ACCEPT_TENANT_CANCEL_BUTTON: "accept-tenant-cancel-button",
  },
  ACCEPT_IMAGE_FORMAT: {
    "image/png": [".png"],
    "image/jpeg": [".jpg", ".jpeg"],
  },
};
